### ISSUE TITLE
TypeError: Cannot read property 'Device' of undefined

### ISSUE THREAD

**Issue by hakimarx** [CenelKITA22/BOT-IG#2]
`[?] Try to Login . . .
TypeError: Cannot read property 'Device' of undefined
    at Login (/home/a/bot-igeh/botlike.js:44:31)
    at Excute (/home/a/bot-igeh/botlike.js:73:31)
    at /home/a/bot-igeh/botlike.js:111:9
`

kenapa ya bang?

**Comment by ikbalardiansah** [comment]
Sama nih, dah solving belum bang?
